### ISSUE TITLE
[Feature Request] Open "Files"  and "restart wsa" option in context menu

### ISSUE THREAD

**Issue by rp1231** [infinitepower18/WSA-SystemControl#1]
Open "Files"  and "restart wsa" option in context menu

**Comment by infinitepower18** [comment]
Hi, I'm really sorry it took so long but the Files option is now available in [v1.0.0](https://github.com/infinitepower18/WSA-SystemControl/releases/tag/v1.0.0)!

I'm still looking into the possibility of adding the reboot option so I'll keep this issue open for now.

**Comment by infinitepower18** [comment]
I will try to get this solved soon. Also, the prerelease version should be uninstalled before installing the 1.0.0 version. As there has been a change in the installer used, it most likely won't update the old version. But future releases after 1.0.0 should be able to update as normal.

**Comment by infinitepower18** [comment]
The multiple instance issue has been fixed in version 1.0.1.

Unfortunately it's currently not possible to add the reboot option, should that change in the future however, I will try to implement it.

I will be closing this issue now, thanks for being patient with me and I hope the latest update works well for you.
